CREATE TABLE IF NOT EXISTS shuttle_driver (
    driver_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    phone VARCHAR(32),
    vehicle_name VARCHAR(80),
    vehicle_number VARCHAR(40),
    profile_info VARCHAR(240),
    approved_by INT NULL,
    approved_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_shuttle_driver_status CHECK (status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT fk_shuttle_driver_user FOREIGN KEY (user_id) REFERENCES `user` (user_id),
    CONSTRAINT fk_shuttle_driver_approved_by FOREIGN KEY (approved_by) REFERENCES `user` (user_id),
    INDEX idx_shuttle_driver_status (status),
    INDEX idx_shuttle_driver_approved_by (approved_by)
);

CREATE TABLE IF NOT EXISTS shuttle_trip (
    trip_id INT AUTO_INCREMENT PRIMARY KEY,
    driver_id INT NOT NULL,
    route VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
    scheduled_start_at DATETIME NOT NULL,
    started_at DATETIME NULL,
    ended_at DATETIME NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    last_location_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_shuttle_trip_route CHECK (route IN ('Kuril', 'Notun Bazar', 'Aftab-Nagor')),
    CONSTRAINT chk_shuttle_trip_status CHECK (status IN ('scheduled', 'active', 'in_progress', 'completed', 'cancelled')),
    CONSTRAINT chk_shuttle_trip_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_shuttle_trip_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT fk_shuttle_trip_driver FOREIGN KEY (driver_id) REFERENCES `user` (user_id),
    INDEX idx_shuttle_trip_route_status_updated (route, status, updated_at),
    INDEX idx_shuttle_trip_driver_status_updated (driver_id, status, updated_at),
    INDEX idx_shuttle_trip_status_scheduled (status, scheduled_start_at)
);

CREATE TABLE IF NOT EXISTS shuttle_wait_request (
    wait_request_id INT AUTO_INCREMENT PRIMARY KEY,
    trip_id INT NOT NULL,
    driver_id INT NOT NULL,
    user_id INT NOT NULL,
    latitude DECIMAL(10,7) NOT NULL,
    longitude DECIMAL(10,7) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'waiting',
    decision_at DATETIME NULL,
    inside_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_shuttle_wait_status CHECK (status IN ('waiting', 'accepted', 'inside_shuttle', 'rejected', 'picked', 'cancelled')),
    CONSTRAINT chk_shuttle_wait_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_shuttle_wait_longitude CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT fk_shuttle_wait_trip FOREIGN KEY (trip_id) REFERENCES shuttle_trip (trip_id),
    CONSTRAINT fk_shuttle_wait_driver FOREIGN KEY (driver_id) REFERENCES `user` (user_id),
    CONSTRAINT fk_shuttle_wait_user FOREIGN KEY (user_id) REFERENCES `user` (user_id),
    INDEX idx_shuttle_wait_trip_user_status (trip_id, user_id, status),
    INDEX idx_shuttle_wait_driver_status_created (driver_id, status, created_at),
    INDEX idx_shuttle_wait_trip_status_updated (trip_id, status, updated_at)
);
